CREATE VIEW W_PEDIDOS_POR_CLIENTE AS

SELECT C.CUSTOMER_CITY, C.CUSTOMER_STATE FROM [dbo].[TB_ATC_OLIST_ORDERS] AS O 

INNER JOIN TB_ACT_olist_customers AS C 
ON O.CUSTOMER_ID = C.CUSTOMER_ID

SELECT * FROM W_PEDIDOS_POR_CLIENTE;